[webservers]
prod-app ansible_host=91.207.183.252 ansible_user=deployer ansible_port=2222

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
